from django.contrib import admin

# Register your models here.

from .models import *

admin.site.register(Tipo_Informacao_Principal)
admin.site.register(Tipo_Informacao_Especifica)
admin.site.register(Idade_Instalacao_Desportiva)
admin.site.register(Balneario)
admin.site.register(Sala_Massagem)
admin.site.register(Sala_Preparacao)
admin.site.register(Sala_Aquecimento)
admin.site.register(Arrecadacao_Material_Desportivo)
admin.site.register(Tribuna_Cabina_Comunicacao_Social)
admin.site.register(Piscinas)
admin.site.register(Bancadas)
admin.site.register(Tipos_Meios_Hidricos_Usados)
admin.site.register(Informacoes_Adicionais)
admin.site.register(Transportes_Publicos)
admin.site.register(Parques_Estacionamento)
admin.site.register(Parques_Estacionamento_Bicicletas_Motociclos)
admin.site.register(Outros_Parques_estacionamento)
admin.site.register(Instalacao_Menos_400_M)
admin.site.register(Instalacao_Inserida_Em)
admin.site.register(Turismo)
admin.site.register(Acessibilidade_Universal)
admin.site.register(Principais_Tipos_Consumos_Custos_Fontes_Energeticas_Nao_Renovaveis)
admin.site.register(Principais_Tipos_Consumos_Custos_Fontes_Energeticas_Renovaveis)
admin.site.register(Consumos_Energeticos_Anuais)
admin.site.register(Custos_Energeticos_Anuais)
admin.site.register(Media_Numeros_Utilizadores_Anuais)
admin.site.register(Iluminacao)
admin.site.register(Climatizacao_Ventilacao)
admin.site.register(Observacoes)
admin.site.register(Custo_Total_Agua_Anual)
admin.site.register(Principais_Consumos_Fontes_Abastecimento_Agua)
admin.site.register(Descricao_Area_Ambiental)
admin.site.register(Tipo_Producao_Residuos)
admin.site.register(CO2_Equivalente)
admin.site.register(Carbono_Associado)
admin.site.register(Tarifa_Media)
admin.site.register(Tipo_Meio_Transporte)
admin.site.register(Tipo_Indicadores_Sustentabilidade)
admin.site.register(Modalidade_Atividades)
