# Generated by Django 5.0 on 2024-05-28 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(max_length=1000)),
                ('tipo', models.CharField(choices=[('NUMERO_INTEIRO', 'Número Inteiro'), ('TEXTO_LIVRE', 'Texto Livre'), ('ESCOLHA_MULTIPLA_UNICA', 'Escolha Múltipla Única'), ('ESCOLHA_MULTIPLA_VARIAS', 'Escolha Múltipla Várias'), ('FICHEIRO', 'Ficheiro'), ('CAMPO_AUTOMATICO', 'Campo Automático'), ('MES', 'Mês')], max_length=30, null=True)),
                ('resposta_permite_repetidos', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SubTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('resposta_duplicavel', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem_perguntas_formulario', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadePergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unidade', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Entidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Instalacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, null=True)),
                ('morada', models.CharField(blank=True, max_length=100, null=True)),
                ('distrito', models.CharField(blank=True, max_length=100, null=True)),
                ('concelho', models.CharField(blank=True, max_length=100, null=True)),
                ('freguesia', models.CharField(blank=True, max_length=100, null=True)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('submetido', models.BooleanField(blank=True, default=False, null=True)),
                ('entidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instalacoes', to='formularioInstituicoes.entidade')),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('instalacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='formularioInstituicoes.instalacao')),
                ('questionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='formularioInstituicoes.questionario')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.CharField(max_length=100)),
                ('pergunta', models.ManyToManyField(related_name='opcoes', to='formularioInstituicoes.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.FileField(blank=True, upload_to='media/')),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='formularioInstituicoes.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='formularioInstituicoes.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaNumerica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(blank=True)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostasNumericas', to='formularioInstituicoes.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostasNumericas', to='formularioInstituicoes.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaTextual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(blank=True, max_length=100)),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostasTextuais', to='formularioInstituicoes.avaliacao')),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostasTextuais', to='formularioInstituicoes.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='subtema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularioInstituicoes.subtema'),
        ),
        migrations.AddField(
            model_name='subtema',
            name='tema',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='formularioInstituicoes.tema'),
        ),
        migrations.AddField(
            model_name='questionario',
            name='temas',
            field=models.ManyToManyField(blank=True, related_name='questionarios', to='formularioInstituicoes.tema'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularioInstituicoes.unidadepergunta'),
        ),
    ]
