# Generated by Django 4.0.6 on 2024-02-21 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='tema',
        ),
        migrations.AlterField(
            model_name='questionario',
            name='perguntas',
            field=models.ManyToManyField(blank=True, null=True, related_name='questionarios', to='formularioInstituicoes.pergunta'),
        ),
        migrations.CreateModel(
            name='SubTema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtemas', to='formularioInstituicoes.tema')),
            ],
        ),
        migrations.AddField(
            model_name='pergunta',
            name='subtema',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='formularioInstituicoes.subtema'),
        ),
    ]
