# Generated by Django 5.0 on 2024-04-20 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilizador',
            name='entidade',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formularioInstituicoes.entidade'),
        ),
    ]
