# Generated by Django 5.0 on 2024-04-21 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0002_utilizador_entidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pergunta',
            name='obrigatoria',
        ),
        migrations.AddField(
            model_name='utilizador',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
