# Generated by Django 4.0.6 on 2024-02-23 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0003_remove_questionario_perguntas_questionario_temas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resposta',
            name='pergunta',
        ),
        migrations.CreateModel(
            name='TipoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_respostas', to='formularioInstituicoes.pergunta')),
            ],
        ),
        migrations.AddField(
            model_name='resposta',
            name='tipo_resposta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='formularioInstituicoes.tiporesposta'),
        ),
    ]
