# Generated by Django 5.0 on 2024-04-27 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0003_remove_pergunta_obrigatoria_utilizador_aprovado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pergunta',
            old_name='resposta_duplicavel',
            new_name='resposta_permite_repetidos',
        ),
    ]
