# Generated by Django 4.0.4 on 2024-04-29 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formularioInstituicoes', '0004_rename_resposta_duplicavel_pergunta_resposta_permite_repetidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='entidade',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Utilizador',
        ),
    ]
