# Generated by Django 4.0.4 on 2024-05-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInstituicoes', '0006_alter_entidade_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entidade',
            name='nome',
        ),
        migrations.AddField(
            model_name='tema',
            name='ordem_perguntas_formulario',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
